In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy's main datatype is ndarray
arr1 = np.array([1,2,3])

In [3]:
arr1 #this is a vector

array([1, 2, 3])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2  = np.array([[1,2,3],
                  [4,5,6]])

In [6]:
arr2 #this is a matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr3 = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]]])

In [10]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

# Visual detail
![](anatomy-np-arr.png)

In [14]:
arr1.shape
#3 indexes

(3,)

In [ ]:
arr2.shape
#2 rows 3 columns

In [11]:
arr3.shape
#2 dimensions 3 rows 3 columns

(2, 3, 3)

In [15]:
#to see how many dimensions
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [21]:
#to see the datatype of the array
arr1.dtype, arr2.dtype, arr3.dtype

(dtype('int64'), dtype('int64'), dtype('float64'))

In [23]:
#see how many elements are in the array
arr1.size, arr2.size, arr3.size

(3, 6, 18)

## Introduce pandas

In [24]:
import pandas as pd

In [28]:
#create a data frame from a Numpy arr
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6